# Generated by Django 6.0.3 on 2026-08-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traveller',
        ),
    ]
